name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Run a one-line script
      run: curl -Lo ./kind https://github.com/kubernetes-sigs/kind/releases/download/v0.5.1/kind-$(uname)-amd64
    - name: chmod kind
      run: chmod +x ./kind
    - name: download kubectl
      run: curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
    - name: chmod kubectl
      run: chmod +x ./kubectl
    - name: create cluster
      run: ./kind create cluster --config config.yml
    - name: show cluster info
      run: KUBECONFIG="$(./kind get kubeconfig-path --name="kind")" ./kubectl cluster-info

